
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author crist
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrnPrincipal
     */
    private static FrmPrincipal instancia;

    private FrmPrincipal() {
        initComponents();
        this.setTitle("El Juego de Timbiriche");
        this.setLocationRelativeTo(null);
        

    }

    public static FrmPrincipal getInstance() {
        if (instancia == null) {
            instancia = new FrmPrincipal();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        btnImgresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 520));

        pnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnPrincipal.setPreferredSize(new java.awt.Dimension(760, 520));
        pnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImgresar.setBackground(new java.awt.Color(0, 51, 255));
        btnImgresar.setFont(new java.awt.Font("Fugaz One", 0, 14)); // NOI18N
        btnImgresar.setForeground(new java.awt.Color(255, 255, 255));
        btnImgresar.setText("Crear Partida");
        btnImgresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)
        );
        btnImgresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImgresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgresarActionPerformed(evt);
            }
        });
        pnPrincipal.add(btnImgresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 397, 199, 56));

        lblTitulo.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        lblTitulo.setText("Titulo");
        pnPrincipal.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 93, -1, -1));

        jLabel1.setFont(new java.awt.Font("Fugaz One", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");
        pnPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 233, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Fugaz One", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setToolTipText("Ingresa tu nickname");
        jTextField1.setBorder(null);
        pnPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 198, -1));
        pnPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 210, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImgresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgresarActionPerformed
      
        
        int size = 10;
        FrmSala sala = FrmSala.getInstance(size);
        sala.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnImgresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImgresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
