/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author palom
 */
public class FrmIconos extends javax.swing.JFrame {

    /**
     * Creates new form FrmIconos
     */
    public FrmIconos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOpcionIcono4 = new javax.swing.JButton();
        btnOpcionIcono1 = new javax.swing.JButton();
        btnOpcionIcono2 = new javax.swing.JButton();
        btnOpcionIcono3 = new javax.swing.JButton();
        btnOpcionIcono8 = new javax.swing.JButton();
        btnOpcionIcono5 = new javax.swing.JButton();
        btnOpcionIcono6 = new javax.swing.JButton();
        btnOpcionIcono7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcionIcono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono4.png"))); // NOI18N
        btnOpcionIcono4.setBorder(null);
        btnOpcionIcono4.setContentAreaFilled(false);
        btnOpcionIcono4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 130, 130));

        btnOpcionIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono1.png"))); // NOI18N
        btnOpcionIcono1.setBorder(null);
        btnOpcionIcono1.setContentAreaFilled(false);
        btnOpcionIcono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 130));

        btnOpcionIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono2.png"))); // NOI18N
        btnOpcionIcono2.setBorder(null);
        btnOpcionIcono2.setContentAreaFilled(false);
        btnOpcionIcono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, 130));

        btnOpcionIcono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono3.png"))); // NOI18N
        btnOpcionIcono3.setBorder(null);
        btnOpcionIcono3.setContentAreaFilled(false);
        btnOpcionIcono3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, 130));

        btnOpcionIcono8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono8.png"))); // NOI18N
        btnOpcionIcono8.setBorder(null);
        btnOpcionIcono8.setContentAreaFilled(false);
        btnOpcionIcono8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 130, 130));

        btnOpcionIcono5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono5.png"))); // NOI18N
        btnOpcionIcono5.setBorder(null);
        btnOpcionIcono5.setContentAreaFilled(false);
        btnOpcionIcono5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, 130));

        btnOpcionIcono6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono6.png"))); // NOI18N
        btnOpcionIcono6.setBorder(null);
        btnOpcionIcono6.setContentAreaFilled(false);
        btnOpcionIcono6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 130, 130));

        btnOpcionIcono7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnIcono7.png"))); // NOI18N
        btnOpcionIcono7.setBorder(null);
        btnOpcionIcono7.setContentAreaFilled(false);
        btnOpcionIcono7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionIcono7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpcionIcono7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 130, 130));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecione un avatar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelarBtn.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelarBtn2.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelarBtn2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoIconos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionIcono4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono4ActionPerformed

    private void btnOpcionIcono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono1ActionPerformed
//        ImageIcon imageIcon = new ImageIcon(new ImageIcon("src/img/btnIcono1.png").getImage());
//        FrmPartida fP = new FrmPartida(imageIcon);
//        fP.setVisible(true);
//        dispose();
    }//GEN-LAST:event_btnOpcionIcono1ActionPerformed

    private void btnOpcionIcono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono2ActionPerformed

    private void btnOpcionIcono3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono3ActionPerformed

    private void btnOpcionIcono8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono8ActionPerformed

    private void btnOpcionIcono5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono5ActionPerformed

    private void btnOpcionIcono6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono6ActionPerformed

    private void btnOpcionIcono7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionIcono7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionIcono7ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmPrincipal fP = new FrmPrincipal();
        fP.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIconos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOpcionIcono1;
    private javax.swing.JButton btnOpcionIcono2;
    private javax.swing.JButton btnOpcionIcono3;
    private javax.swing.JButton btnOpcionIcono4;
    private javax.swing.JButton btnOpcionIcono5;
    private javax.swing.JButton btnOpcionIcono6;
    private javax.swing.JButton btnOpcionIcono7;
    private javax.swing.JButton btnOpcionIcono8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
